apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: hg
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

